---
- include: prepare.yml
  tags: prepare tasks

- include: master.yml
  tags: buildbotmaster tasks
  when: master_name is defined

- include: slave.yml
  tags: buildbotslave tasks
  when: slave_name is defined
