---

- name: Install Buildbot CI
  apt: name=buildbot state=present
  sudo: true

- name: Ensure directory for Buildbot is there
  file:
    dest: "{{ buildbot_path }}"
    state: directory

- name: Create master
  command: buildbot create-master {{ master_name }}
    chdir="{{ buildbot_path }}"
    creates="{{ buildbot_path }}/{{ master_name }}"
  when: master_name is defined
  register: master_creation

- name: Configure master
  template:
    src=master.cfg
    dest={{ buildbot_path }}/{{ master_name }}/master.cfg
    owner={{ user }}
  when: master_creation|success
  register: master_config

- name: Start master
  command: buildbot start {{ master_name }}
    chdir="{{ buildbot_path }}"
  when: master_config|success

- name: Create slave
  command: buildslave create-slave {{ slave_name }} {{ master_host }}:{{ master_port }} {{ slave_username }} {{ slave_pass }}
    chdir="{{ buildbot_path }}"
    creates="{{ buildbot_path }}/{{ slave_name }}"
  when: slave_name is defined
  register: slave_creation

- name: Start slave
  command: buildslave start slave
    chdir="{{ buildbot_path }}"
  when: slave_creation|success
