- name: Master | Ensure necesary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_group }}"
  with_items:
    - /opt/buildbot9
    - /usr/local/src/buildbot
  sudo: yes

- name: Master | Download BB9
  get_url:
    url="{{ bb_master_tarball }}"
    dest=/usr/local/src/buildbot/bb9.tar.gz
  sudo: yes

# - name: Master | Untar BB9
#   unarchive:
#     src=/usr/local/src/buildbot/bb9.tar.gz
#     dest=/opt/buildbot9/
#     creates=/opt/buildbot9/buildbot-0.9.0b9
#   sudo: yes
#   sudo_user: "{{ buildbot_user }}"

- name: Extract tarball
  command: "tar xzf /usr/local/src/buildbot/bb9.tar.gz"
  args:
    chdir: /opt/buildbot9
    timeout: 4000
  sudo: yes
  sudo_user: "{{ buildbot_user }}"

- name: Master | build bb9
  command: python setup.py build
    chdir="/opt/buildbot9/{{ bb_master_tarball | basename | regex_replace('\.tar\.gz', '') }}"
    creates="/opt/buildbot9/{{ bb_master_tarball | basename | regex_replace('\.tar\.gz', '') }}/build"
  sudo: yes

- name: Master | install bb9
  command: python setup.py install
    chdir="/opt/buildbot9/{{ bb_master_tarball | basename | regex_replace('\.tar\.gz', '') }}"
    creates="/opt/buildbot9/{{ bb_master_tarball | basename | regex_replace('\.tar\.gz', '') }}/dist"
  sudo: yes

- name: Master | Download packages for Upgrade
  pip:
    name={{ item }}
  with_items:
    - "{{ bb_waterfall_tarball }}"
    - "{{ bb_www_tarball }}"
    - "{{ bb_consoleview_tarball }}"
  sudo: true

- name: Master | Create master
  command: buildbot create-master {{ master_name }}
    chdir="{{ buildbot_path }}"
    creates="{{ buildbot_path }}/{{ master_name }}"
  when: master_name is defined
  register: master_creation
  sudo: yes
  sudo_user: "{{ buildbot_user }}"

- name: Master | Configure master
  template:
    src=master.cfg.0.9
    dest={{ buildbot_path }}/{{ master_name }}/master.cfg
    owner={{ buildbot_user }}
  register: master_config
  notify: start_master
  when: master_name is defined
  sudo: yes
  sudo_user: "{{ buildbot_user }}"
  notify:
    - restart buildbot master

- name: Master | Verify if a configuration for buildbot master exists.
  local_action: stat path="{{ inventory_dir }}/host_files/{{ inventory_hostname }}/{{ master_config_file }}"
  register: p

- name: Master | Add master config file
  copy:
    src={{ inventory_dir }}/host_files/{{ inventory_hostname }}/{{ master_config_file }}
    dest={{ buildbot_path }}/{{ master_name }}/master.cfg
    owner={{ buildbot_user }}
  when: p.stat.exists
  sudo: yes
  sudo_user: "{{ buildbot_user }}"
  notify:
    - restart buildbot master
