- name: Download BB9
  get_url:
    url="{{ bb_master_tarball }}"
    dest=/tmp/bb9.tar.gz

- name: Ensure directory for untar
  file:
    path: "/tmp/bb9"
    state: directory

- name: Untar BB9
  unarchive:
    src=/tmp/bb9.tar.gz
    dest=/tmp/bb9/

- name: build bb9
  command: python setup.py build
    chdir="/tmp/bb9/buildbot-0.9.0b9"
  sudo: yes

- name: install bb9
  command: python setup.py install
    chdir="/tmp/bb9/buildbot-0.9.0b9"
  sudo: yes

- name: Download packages for Upgrade
  pip:
    name={{ item }}
  with_items:
    - "{{ bb_waterfall_tarball }}"
    - "{{ bb_www_tarball }}"
    - "{{ bb_consoleview_tarball }}"
  sudo: true

- name: Create master
  command: buildbot create-master {{ master_name }}
    chdir="{{ buildbot_path }}"
    creates="{{ buildbot_path }}/{{ master_name }}"
  when: master_name is defined
  register: master_creation
  sudo: yes
  sudo_user: "{{ buildbot_user }}"

- name: Configure master
  template:
    src=master.cfg.0.9
    dest={{ buildbot_path }}/{{ master_name }}/master.cfg
    owner={{ buildbot_user }}
  register: master_config
  notify: start_master
  when: master_name is defined
  sudo: yes
  sudo_user: "{{ buildbot_user }}"


- name: Verify if a configuration for buildbot master exists.
  local_action: stat path="{{ inventory_dir }}/host_files/{{ inventory_hostname }}/{{ master_config_file }}"
  register: p

- name: Add master config file
  copy:
    src={{ inventory_dir }}/host_files/{{ inventory_hostname }}/{{ master_config_file }}
    dest={{ buildbot_path }}/{{ master_name }}/master.cfg
    owner={{ buildbot_user }}
  when: p.stat.exists

- name: (re)start_master
  command: buildbot restart {{ master_name }}
    chdir="{{ buildbot_path }}"
  when: master_name is defined
