---
- name: Slave | Ensure directory for untar
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_group }}"
  with_items:
    - /opt/buildbot9
    - /usr/local/src/buildbot
  sudo: yes

- name: Slave | Download BB9
  get_url:
    url="{{ bb_slave_tarball }}"
    dest=/usr/local/src/buildbot/bb9slave.tar.gz
  sudo: yes

- name: Slave | Untar BB9
  unarchive:
    src=/usr/local/src/buildbot/bb9slave.tar.gz
    dest=/opt/buildbot9/
    creates=/opt/buildbot9/buildbot-worker-0.9.0b9
  sudo: yes
  sudo_user: "{{ buildbot_user }}"

- name: Slave | build bb9
  command: python setup.py build
    chdir=/opt/buildbot9/buildbot-worker-0.9.0b9
    creates=/opt/buildbot9/buildbot-worker-0.9.0b9/build
  sudo: yes

- name: Slave | install bb9
  command: python setup.py install
    chdir=/opt/buildbot9/buildbot-worker-0.9.0b9
    creates=/opt/buildbot9/buildbot-worker-0.9.0b9/dist
  sudo: yes

- name: Slave | Download packages for Upgrade
  pip:
    name={{ item }}
  with_items:
    - "{{ bb_waterfall_tarball }}"
    - "{{ bb_www_tarball }}"
    - "{{ bb_consoleview_tarball }}"
  sudo: true

- name: Slave | Create slave
  command: buildslave create-slave {{ slave_name }} {{ master_host }}:{{ master_port }} {{ slave_username }} {{ slave_pass }}
    chdir="{{ buildbot_path }}"
    creates="{{ buildbot_path }}/{{ slave_name }}"
  when: slave_name is defined
  register: slave_creation
  sudo: yes
  sudo_user: "{{ buildbot_user }}"
  notify:
    - restart buildbot slave
